# Available types: MySQL, SQLite
StorageType: sqlite
Database:
  Host: localhost
  # Default port Mysql: 3306
  Port: 3306
  Database: claimcoredatabase
  Username: claimcoreuser
  Password: claimcorepass

Settings:
  Upgrades: true
  Missions: true
  XPSystem: true
  # The plugin's own economy system will work to buy upgrades of the claim, you can get these coins by completing missions
  #
  # If false, vault will be used instead
  Economy: true