Title: "&aSettings"
Pattern:
  - "#########"
  - "#!#@#$#%#"
  - "#########"
Items:
  '!':
    Type: PLAYER_HEAD
    Name: "&c%player_owner%"
    Lore:
      - "&7"
  '@':
    Action: MISSIONS
    Type: PAPER
    Name: "&aMissions"
    Lore:
      - ""
  '$':
    Action: UPGRADES
    Type: EMERALD_BLOCK
    Name: "&aUpgrades"
    Lore:
      - ""
  '%':
    Action: MEMBERS
    Type: PLAYER_HEAD
    Name: "&aMembers"
    Lore:
      - ""