Title: ""
Pattern:
  - "#########"
  - "#!##@$%*#"
  - "#########"
Items:
  '!':
    Type: PLAYER_HEAD
    Name: "&c%player-owner%"
    Lore:
      - "&7"
  '@':
    Type: PAPER
    Name: "&aMissions"
    Lore:
      - ""
  '$':
    Type: EMERALD_BLOCK
    Name: "&aUpgrades"
    Lore:
      - ""
  '%':
    Type: ""
    Name: "&aMembers"
    Lore:
      - ""
  '*':
    Type: DIAMOND_HOE
    Name: "&aClaim chunk"
    Lore:
      - ""