name: ClaimCore
author: GabrielHD55
version: 1.0
api-version: 1.18
main: com.gabrielhd.claimcore.ClaimCore
description: Chunk Claim Core
depend:
  - PlaceholderAPI
softdepend:
  - WorldGuard
  - GriefPrevention
commands:
  party:
    usage: /<command>
    aliases:
      - p
      - claim
  coins:
    usage: /<command>
    aliases:
      - monedas